### PR TITLE
Added Event.With

### PR DESCRIPTION
**Pull request by jilleJr**
- \[x] I've added a new note in the `CHANGELOG.md` file, according to docs:
  https://iver-wharf.github.io/#/development/changelogs/writing-changelogs

## Summary

- Added `logger.Event.WithFunc(func(Event) Event) Event`

## Motivation

Makes it easier to reuse logging fields, such as:

```go
func someFunc(group, name string) {
  log.Debug().
    WithString("group", group).
    WithString("name", name).
    Message("Foo bar.")

  log.Warn().
    WithString("group", group).
    WithString("name", name).
    Message("Oh no, but it's ok.")

  err := someOtherFunc(group, name)
  log.Error().
    WithString("group", group).
    WithString("name", name).
    WithError(err).
    Message("Oh no, it's not ok.")
}
```

vs:

```go
func someFunc(group, name string) {
  logArgs := func(ev logger.Event) logger.Event {
    return ev.
      WithString("group", group).
      WithString("name", name)
  }

  log.Debug().WithFunc(logArgs).Message("Foo bar.")

  log.Warn().WithFunc(logArgs).Message("Oh no, but it's ok.")

  err := someOtherFunc(group, name)
  log.Error().WithFunc(logArgs).WithError(err).Message("Oh no, it's not ok.")
}
```

### CODE REVIEW

**Comment by jilleJr** [comment]
Something that might have been nicer would be if it was a store of function calls or something instead, so that the interface would look like this:

```go
func someFunc(group, name string) {
  logArgs := log.Prepare().
      WithString("group", group).
      WithString("name", name)

  log.Debug().With(logArgs).Message("Foo bar.")

  log.Warn().With(logArgs).Message("Oh no, but it's ok.")

  err := someOtherFunc(group, name)
  log.Error().With(logArgs).WithError(err).Message("Oh no, it's not ok.")
}
```

Thoughts?

**Comment by jilleJr** [comment]
Other idea: Abuse `context.Context`!

**Comment by Alexamakans** [comment]
Nice!

I like the suggestion in https://github.com/iver-wharf/wharf-core/pull/29#issuecomment-912306055 more.

**Comment by fredx30** [comment]
> Something that might have been nicer would be if it was a store of function calls or something instead, so that the interface would look like this:
> 
> ```go
> func someFunc(group, name string) {
>   logArgs := log.Prepare().
>       WithString("group", group).
>       WithString("name", name)
> 
>   log.Debug().With(logArgs).Message("Foo bar.")
> 
>   log.Warn().With(logArgs).Message("Oh no, but it's ok.")
> 
>   err := someOtherFunc(group, name)
>   log.Error().With(logArgs).WithError(err).Message("Oh no, it's not ok.")
> }
> ```
> 
> Thoughts?
> This suggestion would probably involve a more code though. But it produces less code for the user as you don't have to declare a function, and if done right you could extend them like so:
> 
> ```go
> func someFunc(group, name string) {
>   logArgs := log.Prepare().
>       WithString("group", group).
>       WithString("name", name)
> 
>   log.Debug().With(logArgs).Message("Foo bar.")
> 
>   log.Warn().With(logArgs).Message("Oh no, but it's ok.")
> 
>   err := someOtherFunc(group, name)
>   logArgsAndErr := logArgs.WithError(err)
>   log.Debug().With(logArgs).Message("Doesn't have an 'error' field.")
>   log.Error().With(logArgsAndErr).Message("Oh no, it's not ok.")
> }
> ```

Im a big fan of [KISS](https://en.wikipedia.org/wiki/KISS_principle). In this case i believe adding alot more code and complexity for something i dont see a vital use case for would directly violate the kiss principle. 

As is it adds value without alot more code and the complexity is optional. That seems good to me. If further complexity is added in the form of large amounts of code bloat we should also have a good way of hiding that complexity deeper such that it does not interfear with the ability to gain an oversight of the big picture.

**Review by fredx30 — APPROVED** [review]

**Comment by jilleJr** [comment]
> Im a big fan of [KISS](https://en.wikipedia.org/wiki/KISS_principle). In this case i believe adding alot more code and complexity for something i dont see a vital use case for would directly violate the kiss principle.
> 
> As is it adds value without alot more code and the complexity is optional. That seems good to me. If further complexity is added in the form of large amounts of code bloat we should also have a good way of hiding that complexity deeper such that it does not interfear with the ability to gain an oversight of the big picture.

While I'm not a fan of that acronym (it's quite offensive), I am a fan of that idea of keeping things simple. I want to rename it though as just `With` should be reserved to something truly generic, such as the dismissed idea you quoted.

Renaming to `WithFunc`. If you have other naming ideas then please shoot. Maybe `WithF` to keep it even shorter?

**Review by Alexamakans — APPROVED** [review]

**Comment by Alexamakans** [comment]
> > Im a big fan of [KISS](https://en.wikipedia.org/wiki/KISS_principle). In this case i believe adding alot more code and complexity for something i dont see a vital use case for would directly violate the kiss principle.
> > As is it adds value without alot more code and the complexity is optional. That seems good to me. If further complexity is added in the form of large amounts of code bloat we should also have a good way of hiding that complexity deeper such that it does not interfear with the ability to gain an oversight of the big picture.
> 
> While I'm not a fan of that acronym (it's quite offensive), I am a fan of that idea of keeping things simple. I want to rename it though as just `With` should be reserved to something truly generic, such as the dismissed idea you quoted.
> 
> Renaming to `WithFunc`. If you have other naming ideas then please shoot. Maybe `WithF` to keep it even shorter?

I prefer `WithFunc`, it's not that much longer than `WithF`, and can't be accidentally confused for the `-f` suffix meaning of e.g. `Messagef` or `Printf` etc.
Since the calls are typically chained and put on multiple lines I don't think shortening it has a real impact.

**Pull request merged**
